version: "3.8"

services:
  geth:
    image: ethereum/client-go
    container_name: geth_dev_node
    ports:
      - "8545:8545"
      - "30303:30303"
    command:
      [
        "--dev",
        "--http",
        "--http.addr", "0.0.0.0",
        "--http.api", "eth,net,web3,personal",
        "--http.corsdomain", "*",
        "--allow-insecure-unlock",
      ]
